### PR TITLE
Adding Character Screen

### PR DESCRIPTION
**Pull request by pranatimittal**

### CODE REVIEW

**Comment by starboi02** [comment]
@pranatimittal please attach ss

**Comment by pranatimittal** [comment]
Screenshot (109)
Screenshot (110)

**Review by starboi02 — CHANGES_REQUESTED** [review]
@pranatimittal looks good use ``--`` as default for empty fields. And remove `` \n`` also

**Comment by pranatimittal** [comment]
I have made the required changes
Screenshot (111)

**Review by starboi02 — CHANGES_REQUESTED** [review]
@pranatimittal you have changed methods inside ``CharacterItem`` but you should rather let it remain same and apply your logic after receiving the list from these methods as changing the methods would intervene with the Database Handler.

**Comment by pranatimittal** [comment]
Okay, Done

**Review by starboi02 — APPROVED** [review]

**Pull request merged**
