### PR TITLE
Toolbar colour changed

### PR DESCRIPTION
**Pull request by CadencePrestissimo**

### CODE REVIEW

**Comment by CadencePrestissimo** [comment]
Screenshot (85)

**Comment by CadencePrestissimo** [comment]
Screenshot (88)

I tried a new way to show the things by changing the layout !
These changes are not there in this branch and PR.

**Review by starboi02 — CHANGES_REQUESTED** [review]
I really liked the Toolbar but can you show me how would it look after search view is expanded.
And dont change the recycler view font and color scheme as we probably would be using a custom font later.

**Comment by CadencePrestissimo** [comment]
Screenshot (89)
Screenshot (90)


Final ---------------------------
Screenshot (94)

**Comment by CadencePrestissimo** [comment]
I have changed row .xml too and some files like style.xml
Should I commit the changes ?

**Comment by starboi02** [comment]
@CadencePrestissimo dont change row.xml and check the search logo its not transparent there's a gray patch on the toolbar. Choose a different color for the background and recycler view

**Comment by CadencePrestissimo** [comment]
ohk , will leave the row.xml as it is
the grey patch is there cause when search view will expand it will be easier and clear yo type on that grey expanded patch rather than on the imaged toolbar

**Comment by CadencePrestissimo** [comment]
Screenshot (95)


How about this colour?

**Comment by starboi02** [comment]
@CadencePrestissimo use `#656767 ` as the background color for both root layout and recycler view.

**Comment by CadencePrestissimo** [comment]
Changed the colour !

**Review by starboi02 — APPROVED** [review]

**Pull request merged**
