### PR TITLE
Children Attribute added

### PR DESCRIPTION
**Pull request by DevilAJ**
I have created children attribute in character class and initialized in contructor.

image

Method for same is also created.

image

### CODE REVIEW

**Comment by starboi02** [comment]
@DevilAJ there are some heavy conflicts which cant be resolved from here use command line to resolve them. May be u didnt update the local repo before making changes.

**Comment by DevilAJ** [comment]
These are the only diffrence in my code and main code

image

**Comment by starboi02** [comment]
@DevilAJ your changes are right but the conflict is occuring because you didnt update your project before making changes.

**Comment by DevilAJ** [comment]
Ohh I get it

**Comment by starboi02** [comment]
@DevilAJ in the resolve conflict area click on ``` Use the command line ``` it will provide you the steps to follow to resolve this conflict

**Pull request closed without merging**
