### PR TITLE
added splash screen

### PR DESCRIPTION
**Pull request by Devildarkfire**
Added Splash Screen #1

### CODE REVIEW

**Comment by starboi02** [comment]
@Devildarkfire please provide ss of splash screen

**Comment by Devildarkfire** [comment]
# screenshot
ScreenShot

**Comment by starboi02** [comment]
@Devildarkfire replace the music icon with some GoT logo and change the background color to give it a GoT themed feel : )

**Comment by Devildarkfire** [comment]
# screenshot of updated background

**Comment by starboi02** [comment]
@Devildarkfire ss is not visible

**Comment by Devildarkfire** [comment]
# ss of updated background
ss

**Pull request merged**
