### PR TITLE
Added searchView in toolbar

### PR DESCRIPTION
**Pull request by Mandar16**

### CODE REVIEW

**Comment by starboi02** [comment]
@Mandar16 attach ss also.

**Comment by starboi02** [comment]
@Mandar16 and also remove `app:layout_constraintBottom_toBottomOf="parent"` from line 26 of activity_main.xml as it will make the view in the center of the screen but we want it to be aligned to the top.

**Comment by Mandar16** [comment]
Ok will do that.

**Comment by starboi02** [comment]
@Mandar16 ss?

**Comment by Mandar16** [comment]
ssActivity_main
ssSearchView

**Pull request merged**
