### PR TITLE
modified row.xml file

### PR DESCRIPTION
**Pull request by Devildarkfire**
row.xml has modified  #13

### CODE REVIEW

**Comment by starboi02** [comment]
@Devildarkfire please attach ss with every PR you make as it's considered a good practice and makes it easier for the assigner to review the changes.

**Comment by Devildarkfire** [comment]
ok I will attach the ss every pr
ss

**Comment by starboi02** [comment]
@Devildarkfire the Heart image is not looking like heart tbh style it better use `#232323` as background color for row.xml and align character image to the left side increase its radius and try to style this whole better :)

**Comment by Devildarkfire** [comment]
ss attached of changed xml file
scrrenShot

**Comment by starboi02** [comment]
@Devildarkfire there is still margin for improvement :)

**Comment by Devildarkfire** [comment]
margin applied and background set to dark theme 
ss

**Comment by starboi02** [comment]
@Devildarkfire resolve the conflicts also

**Comment by Devildarkfire** [comment]
Conflict solved

**Comment by starboi02** [comment]
@Devildarkfire still some conflicts are left

**Review by starboi02 — APPROVED** [review]

**Pull request closed without merging**
